name: Finetuning LLMs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download-llm:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zcaudate-xyz/infra-ai-python:main

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

#      - name: Login to Hugging Face Hub (Optional)
#        env:
#          HF_TOKEN: ${{ secrets.HF_TOKEN }}
#        run: |
#          huggingface-cli login --token $HF_TOKEN

      - name: Finetune bigcode/starcoder2-3b
        run: python3 ./finetune_codestar2_3b.py
